'use strict';

// scripts/test-browser-fallback.js is Emma's go/no-go probe: `npm run
// test-browser -- --live` on the production Mac is the precondition for
// re-enabling the CoStar sites. Two things must therefore be true of it, and
// both are pinned here — offline, with no land-listing domain contacted:
//
//   1. It calls a block a block. Detection must be the SHARED chokepoint
//      (lib/block-markers.js), not a private marker list that can rot behind
//      it and report a refusing site as healthy.
//   2. It probes the URLs the scraper actually fetches — generated by the
//      parsers' own buildSearchUrls, not hand-written.
//
// Requiring the script must not launch a browser or hit the network; that it
// can be required at all is the first assertion.

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const probe = require('../scripts/test-browser-fallback');
const { BLOCK_MARKERS, isBlockedHtml } = require('../lib/block-markers');
const { parsers } = require('../lib/parsers');

const FIXTURE_DIR = path.join(__dirname, 'fixtures');

// --- 1. Detection agrees with the shared chokepoint -----------------------

test('the probe verdict flags every marker the shared chokepoint knows', () => {
  for (const marker of BLOCK_MARKERS) {
    const html = `<html><head><title>Attn</title></head><body>${marker}</body></html>`;
    assert.equal(isBlockedHtml(html), true, `chokepoint must flag "${marker}"`);
    assert.equal(probe.verdict(html, 200), '🚫 challenge page',
      `probe must flag "${marker}" — a private marker list here would rot behind block-markers.js`);
  }
});

test('the probe verdict flags challenge markers the old hand-rolled regex missed', () => {
  // These five are in BLOCK_MARKERS but were absent from the regex the script
  // used to carry, so each one used to be reported as "✅ real page".
  for (const marker of ['perimeterx', 'cf-browser-verification', 'cf-challenge',
    'request unsuccessful', 'are you a robot']) {
    assert.ok(BLOCK_MARKERS.includes(marker), `${marker} should be a shared marker`);
    assert.equal(probe.verdict(`<html><body>${marker}</body></html>`, 200), '🚫 challenge page');
  }
});

test('the probe verdict still reports HTTP status failures and real pages', () => {
  assert.equal(probe.verdict('<html></html>', 403), '❌ HTTP 403');
  const realPage = fs.readFileSync(path.join(FIXTURE_DIR, 'landflip-kentucky-search.html'), 'utf8');
  assert.match(probe.verdict(realPage, 200), /^✅ real page \(/, 'output format is unchanged');
});

// --- 2. No false positives on real pages ----------------------------------

test('isBlockedHtml classifies every real-page fixture as NOT blocked', () => {
  // The probe now trusts the chokepoint completely, so a chokepoint that
  // misfired on a real results page would block a healthy site's re-enable.
  // Every fixture in test/fixtures/ is a real captured page.
  const fixtures = fs.readdirSync(FIXTURE_DIR).filter(f => f.endsWith('.html'));
  assert.ok(fixtures.length >= 8, 'the sweep must cover the whole fixture directory');
  for (const file of fixtures) {
    const html = fs.readFileSync(path.join(FIXTURE_DIR, file), 'utf8');
    assert.equal(isBlockedHtml(html), false, `${file} is a real page and must not be flagged`);
    assert.notEqual(probe.verdict(html, 200), '🚫 challenge page', `${file} via the probe`);
  }
});

// --- 3. Probe URLs come from the parsers ----------------------------------

test('live probe URLs are generated by the parsers, not hand-written', () => {
  const expected = ['landwatch', 'landcom', 'landfarm']
    .map(key => parsers[key]().buildSearchUrls([{ county: 'Johnson', state: 'KY' }])[0].url);

  assert.deepEqual(probe.LIVE_URLS, expected);
  assert.deepEqual(probe.buildLiveProbeUrls(), expected);
});

test('the LandAndFarm probe URL tracks the parser shape and stays a Kentucky county search', () => {
  const landfarmUrl = probe.LIVE_URLS[2];
  const parserUrl = parsers.landfarm().buildSearchUrls([{ county: 'Johnson', state: 'KY' }])[0].url;

  assert.equal(landfarmUrl, parserUrl,
    'the probe must fetch exactly what the scrape fetches — no invented URL shape');
  assert.match(landfarmUrl, /^https:\/\/www\.landandfarm\.com\//);
  assert.match(landfarmUrl.toLowerCase(), /kentucky/, 'original probe intent: a Kentucky county search');
  assert.match(landfarmUrl.toLowerCase(), /johnson/);
});

test('every probe URL belongs to its own site and is page 1', () => {
  const hosts = ['www.landwatch.com', 'www.land.com', 'www.landandfarm.com'];
  probe.LIVE_URLS.forEach((url, i) => {
    assert.equal(new URL(url).host, hosts[i]);
    if (hosts[i] === 'www.landandfarm.com') {
      // Capture-proven: page 1 is the bare canonical county URL — the capture
      // never links a /page-1 segment anywhere, so a `page[-=]1` regex would
      // fail on the one shape the site actually serves.
      assert.ok(url.endsWith('-county-land-for-sale/') && !/page[-=]\d/.test(url),
        'landfarm page 1 is the bare canonical URL, no page segment');
    } else {
      assert.match(url, /page[-=]1(&|$)/, 'probes stay on page 1 — this is a diagnostic, not a scrape');
    }
  });
});
